services:
  - type: web
    name: my-python-app
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt --prefer-binary
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true