services:
  - type: web
    name: my-fastapi-app
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --prefer-binary
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    autoDeploy: true