services:
  - type: web
    name: qc-automation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY_1
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false
      - key: OCR_API_URL
        value: https://velan2904-image-ocr.hf.space/ocr
      - key: PYTHON_VERSION
        value: 3.11.0